# Generated by Django 4.1.2 on 2023-05-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("create_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
